### ISSUE TITLE
Shape of Tweet dataset

### ISSUE THREAD

**Issue by jflanaga** [timothyrenner/partisan_hashtags#1]
Hi,
sorry for opening an issue on such an old repo, but it looks interesting. Anyways, I'm having trouble getting `jq` to format the tweets correctly (basically, I'm piping the json file to the command, but nothing is happening). I eventually have to CTRL C to stop the process. 

I have other ways of parsing the json, so that's not crucial. However, I don't see any mention of what the proper format of the dataset should be. Reading the jq command, I'm imagining that you'll have n rows of each tweet, with n equal to the number of the hashtags in a given combination (so if a tweet has two hashtags, it will have two rows: one row will be hashtagA hashtagB and the next will be hashtagB hashtagA. Is that correct? 

As I said, I know it's an old repo, but the analysis looks useful.

**Comment by timothyrenner** [comment]
Hey thanks for your interest! You caught me at the perfect time. 

What that command does (or rather what it's _supposed_ to do :) ) is put each hashtag on it's own row, so a hypothetical Charlie Sheen tweet with four hashtags will produce this:

```
charliesheen,Wed Apr 1 <time stuff here>, 1234567, winning
charliesheen,Wed Apr 1 <time stuff here>, 1234567, tigerblood
charliesheen,Wed Apr 1 <time stuff here>, 1234567, tigerking
charliesheen,Wed Apr 1 <time stuff here>, 1234567, drugs
```

Then there's one more preprocessing step which looks like (sorry it's been a while) I cleaned the raw data a little bit and isolated only a small time slice for analysis.

The links are formed later on in the notebook using joins and that's fed to networkx. Does that help?

**Comment by timothyrenner** [comment]
Docs on jq combinations operator: https://stedolan.github.io/jq/manual/#combinations,combinations(n)

**Comment by jflanaga** [comment]
Great. Thanks. I've already processed the tweets into Pandas If it's just a matter of getting each hashtag on a separate line, I can do that with 

```
df['hashtags'].str_split().explode()
```

I read the documentation a bit too quickly. I thought it would give us combinations. 

Thanks again.If I know the shape of the dataset, I should be able to get the ret.
